version: '3'
services:
  web:
    image: mirror-reg.cloud.transfond.ro:5000/transfond/node:latest
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: mirror-reg.cloud.transfond.ro:5000/transfond/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdatabase
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
